---
title: "R buddies session 4 - version control"
output: github_document
author: "Noëlle V. Schenk"
date: "2023-04-27"
editor_options: 
  chunk_output_type: inline
---

# Aim
A collection of ressources to install version control, and to practice it's use.


# Requirements

A Computer or Laptop where you have R and RStudio installed, and where you have the rights to install new software.

```{r}
# install.packages("usethis")
library(usethis)
```



# Part 1 : Install version control

## Install git

Try to set up git and connect it to RStudio. For this, follow the instructions under point 6 in [this](https://happygitwithr.com/install-git.html) tutorial.

If you run into problems, consider the Frequently Asked Questions (FAQ) section of this documents and feel free to ask.


## Configure git

Configure git on your PC/ Laptop. Follow the instructions under point 7 in [this](https://happygitwithr.com/install-git.html) tutorial (same as above). Please *note* : You do not need a GitHub account to follow this tutorial! The instructions just want to point out that IF you consider a GitHub account, you should use the email address you WOULD USE for this GitHub account in your configuration file.

Under Point 7.1.2, please use the word "main" as default name for initial branch.



## Connect git and RStudio to GitHub

Try to connect git and RStudio to GitHub following points 4 (only if you want GitHub) and 8 (everyone) [this](https://happygitwithr.com/install-git.html) tutorial (same as above):  (points 4 and 8 in the tutorial)

If you run into problems, consider the Frequently Asked Questions (FAQ) section of this documents and feel free to ask.



# Frequently Asked Questions

## What is the difference between git and GitHub?

git is the version control program. It does everything we discussed during the lecture, it allows you to document changes in your script and offers an environment to keep those updates organised, and it connects with RStudio.

GitHub is just an online repository for you where you can share your code online. It is specialised on publishing code under version control using git. In other words, it's a platform where you share your scripts. GitHub is often used for software in beta-status, i.e. for software which is awaiting changes in the near future. To make your software (your code) public in the long run, we in science need other platforms like Zenodo. They guarantee to keep the software available long enough (usually 10 years) under a stable identification number (doi). GitHub is therefore rather a platform for code in progress.


## Connect an existing project to GitHub

There are basically 2 solutions to this. One is rather a [workaround](https://github.com/biodiversity-exploratories-synthesis/Synthesis_tutorials/blob/main/RStudio_GitHub_FAQ.md), the other is an actual [solution](https://hansenjohnson.org/post/sync-github-repository-with-existing-r-project/) (but in my experience way harder to implement)








# TODO

- Nächstes Mal : eine Anleitung/ tutorial suchen, um git NUR locally zu haben.
    während dem kurs war es verwirrend, weitere Tutorials zu suchen

Probleme : 
- user.name und user.email angeben (via konsole)
- git.exe finden : Im Git bash properties schauen, wo pfad ist
- Connect an existing project to GitHub (Eva)


